# Generated by Django 5.0.6 on 2024-06-05 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Encode_Decode_app', '0002_empregistration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empregistration',
            name='phoneNumber',
            field=models.IntegerField(),
        ),
    ]
