# Generated by Django 5.0.6 on 2024-06-25 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Encode_Decode_app', '0004_delete_emploginmodel_delete_employee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empregistration',
            name='confirm_Password',
        ),
    ]
