# Generated by Django 5.0.6 on 2024-06-30 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Encode_Decode_app', '0005_remove_empregistration_confirm_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empregistration',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='empregistration',
            name='password',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='empregistration',
            name='phoneNumber',
            field=models.IntegerField(unique=True),
        ),
    ]
