# Generated by Django 5.0.6 on 2024-07-02 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Encode_Decode_app', '0007_contactmessage_alter_empregistration_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmessage',
            name='number',
            field=models.IntegerField(max_length=10),
        ),
    ]
