# Generated by Django 5.0.6 on 2024-07-02 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Encode_Decode_app', '0008_alter_contactmessage_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmessage',
            name='number',
            field=models.CharField(max_length=10),
        ),
    ]
