# Generated by Django 5.0.6 on 2024-07-11 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Encode_Decode_app', '0010_empregistration_is_verified_empregistration_otp'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTPverify',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('otp', models.CharField(blank=True, max_length=6)),
            ],
        ),
        migrations.RemoveField(
            model_name='empregistration',
            name='is_verified',
        ),
        migrations.RemoveField(
            model_name='empregistration',
            name='otp',
        ),
    ]
