# Generated by Django 5.0.6 on 2024-07-12 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Encode_Decode_app', '0011_otpverify_remove_empregistration_is_verified_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EmpRegistration',
            new_name='Registration',
        ),
    ]
