# Generated by Django 5.0.6 on 2024-08-07 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Encode_Decode_app", "0014_aeshistory_key"),
    ]

    operations = [
        migrations.AddField(
            model_name="aeshistory",
            name="flag",
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="base64history",
            name="flag",
            field=models.CharField(max_length=20, null=True),
        ),
    ]
