# Generated by Django 5.0.6 on 2024-08-07 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Encode_Decode_app", "0015_aeshistory_flag_base64history_flag"),
    ]

    operations = [
        migrations.AddField(
            model_name="base64history",
            name="search",
            field=models.CharField(
                blank=True,
                choices=[("decode", "decode"), ("encode", "encode")],
                max_length=100,
            ),
        ),
    ]
