# Generated by Django 5.0.6 on 2024-08-07 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Encode_Decode_app", "0016_base64history_search"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="base64history",
            name="flag",
        ),
    ]
